### ISSUE TITLE
[MINI2] Todo List UI

### ISSUE THREAD

**Issue by jasper200207** [jasper200207/react-todo-list-precourse#7]
- [x] ❗️Todo Item 제목
- [x] ❗️Todo Item 상태 ( 완료, 진행중 )
- [x] ❗️Todo Item 삭제
- [x] ❗️Todo Item 생성
