### ISSUE TITLE
[MINI2] Todo Detail UI

### ISSUE THREAD

**Issue by jasper200207** [jasper200207/react-todo-list-precourse#8]
- [ ] Todo Item 내용 ( 제목, 메모 )
- [ ] Todo Item 삭제
- [ ] Todo Item 수정 ( 제목, 메모, 상태 )
